server:
  servlet:
    session:
      timeout: 30m          # 세션 만료 시간 (30분)
      cookie:
        http-only: true

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  thymeleaf:
    cache: false  
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.eval.domain